### ISSUE TITLE
Stage 2 get-up policy not working well

### ISSUE THREAD

**Issue by xkhainguyen** [RunpeiDong/HumanUP#3]
Hi there,

Thank you for open-sourcing this interesting work. I attempted Stage 2 training using the trajectory data you provided. The get-up policy was trained for 50k learning iterations, but none of the checkpoints seem to work as robustly as described in the paper. Am I missing something?

**Comment by RunpeiDong** [comment]
Hi @xkhainguyen,

Thank you for your interest in our work. Have you rolled out the policy in Sim and did it get up successfully and smoothly?

**Comment by xkhainguyen** [comment]
Hi @RunpeiDong 

Thanks for your response. I was describing simulation evaluation and it didn't work well. The robot struggled to get up, sometimes it worked but it moved backward a lot to balance instead of standing still.

My training looks like this
![Image](https://github.com/user-attachments/assets/968a6b45-5309-45ac-a5c9-bc8689af692e)

**Comment by RunpeiDong** [comment]
Hi @xkhainguyen,

Thanks for the polts. The reward and episode length seem okay but the mean reward is not enough to see everything. Can you show me some videos? We should keep looking at videos to see where is going wrong.

**Comment by xkhainguyen** [comment]
Hi,

This is the [video](https://drive.google.com/file/d/1U1JuzaEY9R0CNC6UixW-721dUcNyvFbU/view?usp=sharing)

Also, about the final pose (right hand up), was it something manually encoded or emerging from the training?

**Comment by RunpeiDong** [comment]
- It seems your policy learns to get up with a very large feet distance. Try to use smaller feet distance regularization with higher reward weights.
- The hand is not manually encoded but emerged from training. I tried to increase regularization on hands but it leads to some behavior not as robust as the current one.

**Comment by RunpeiDong** [comment]
Closed for no further response.

**Comment by xkhainguyen** [comment]
Hi @RunpeiDong,

Sorry for the late response. I used your default configs and deployed sim2sim in Mujoco. It worked quite well.
Was it possible that IsaacGym evaluation was worse because there was some domain randomization?

I tried to deploy the get-up policy on the real robot. It almost worked but encountering overheating issue at the end of the motion => got shut down. 
Have you seen anything like that? Are there any notes on deploying the policy in the real world?

Many thanks!

**Comment by RunpeiDong** [comment]
Hi @xkhainguyen,

I'm glad to hear that your problem has been solved.

For the deployment tips,
- Yes, we sometimes encounter overheating issues during deployment, especially in the upper body. The lower body is typically fine. This is also why we plot Fig 5, since our policy is already yielding a motion that avoids overheating by limiting the usage of arms.
- One very useful tip is that you should do some safety checking during deployment. For example, if some joints apply too large torque, you may want to shut down the policy running automatically to protect the robot. Safety first!
- Other tips are that you should keep looking closely at the motion in the real world compared to the one in the simulation. Observe the robot very carefully to see where needs improvements.
- Also, try more checkpoints. RL yields checkpoints with slightly different robustness.

**Comment by xkhainguyen** [comment]
Thanks for your prompt response!

> Yes, we sometimes encounter overheating issues during deployment, especially in the upper body. The lower body is typically fine. This is also why we plot Fig 5, since our policy is already yielding a motion that avoids overheating by limiting the usage of arms. 

I meant I used your policy but still encountering overheating issues (probably with the upper body). Do I need to do more tuning?

> One very useful tip is that you should do some safety checking during deployment. For example, if some joints apply too large torque, you may want to shut down the policy running automatically to protect the robot. Safety first!

Sounds good! I should use `tau_est` measurements for this, right?

> Other tips are that you should keep looking closely at the motion in the real world compared to the one in the simulation. Observe the robot very carefully to see where needs improvements.

Yes!

> Also, try more checkpoints. RL yields checkpoints with slightly different robustness. 

How can we know which one is better? I normally just look at reward and episode length.

**Comment by RunpeiDong** [comment]
- Seems so, there is nothing special you can do to avoid overheating. You should try to train a safer policy (maybe stronger torque limits).
- That sounds right.
- The reward and episode length do not ensure success or quality. Please always look at the videos carefully, and try to deploy those promising checkpoints.
